### ISSUE TITLE
`forall` is now a reserved keyword in GHC 9.10

### ISSUE THREAD

**Issue by locallycompact** [stevana/quickcheck-state-machine#46] opened 2024-05-25 22:00 UTC
Due to visible type arguments, the word `forall` can no longer be used as the name of a function.

**Comment by jasagredo** [comment] 2024-05-27 14:58
Solved in #47.

**Comment by stevana** [comment] 2024-05-28 06:22
Duplicate of #3.

**Closed** 2024-05-28 06:22 UTC
